apiRules:
- exclude:
    uidRegex: ^TraktNet\.Objects\.Json
    type: Type
- exclude:
    uidRegex: ^TraktNet\.Requests
    type: Type
- include:
    uidRegex: ^TraktNet\.Requests\.Handler\.IHttpClientProvider$
    type: Type
- include:
    uidRegex: ^TraktNet\.Requests\.Handler\.HttpClientProvider$
    type: Type
- include:
    uidRegex: ^TraktNet\.Requests\.Parameters
    type: Type
- exclude:
    uidRegex: ^TraktNet\.Core
    type: Type
- include:
    uidRegex: ^TraktNet\.Core\.TraktConfiguration$
    type: Type
